### ISSUE TITLE
Possible to add more sync modes (ppqn) to Clock external pulse input?

### ISSUE THREAD

**Issue by Torinbob** [zezic/ZZC#31]
Currently Clock syncs to external pulse as bpm or 1 pulse per quarter note (ppqn). As Clock measures the time between the first 2 pulses, it is relatively slow to sync at this frequency. Would it be possible to add at least a 4ppqn option please (for sending a 4x clock) and ideally a 24 ppqn sync option (perhaps in contextual menu setting) which would make syncing much quicker and more responsive when sending a pulse from DAW etc. Thanks

**Comment by zezic** [comment]
Thank you for your request. It's a good idea. I will implement it and let you know.

**Comment by Torinbob** [comment]
Hi Zezic - just wondered if there was any update on this? thanks

**Comment by zezic** [comment]
Hi, @Torinbob, there no updates regarding this yet. At the moment I'm working on documentation for Phaseque which is just was released for Rack 1.1.x. After it I will proceed to feature requests like this and will post to this thread with an update as soon as it will be available.

**Comment by zezic** [comment]
Added in v1.1.1
