### ISSUE TITLE
Be compatible with Rack 1.0

### ISSUE THREAD

**Issue by zezic** [zezic/ZZC#36]

**Comment by VegaDeftwing** [comment]
It would be nice if Clock had an option to output a poly signal with 1x on ch1, 2x on ch2, 4x on ch3 and so on

A module very similar to SH-8 but using polyphonic cables would be nice as well, could have only 2 inputs and 1 output: a monophonic cable for noise, a polyphonic cable for trig and a polyphonic cable for the outputs

Finally, polyphonic output on Phaseque would be great, especially if it were made so multiple patterns could play simultaneously.

**Comment by zezic** [comment]
@VegaDeftwing I will think about this option for clock. Maybe, it will be included as a right-click menu option.

Confirmed polyphonic S&H: #39

Polyphonic output of Phaseque will be implemented for sure, at least for single-at-a-time pattern playback. I will think about multiple parallel patterns playback, it can be a feature for panel extension, thank you for idea.

**Comment by Torinbob** [comment]
Hi Zezic

There is currently a community document tracking progress of plugins towards V1 compatibility. Please would you let me know if you are currently working on that? I could then ask for the status to be updated  to "In progress".

Many thanks.

**Comment by zezic** [comment]
Hello, @Torinbob
Thank you for contacting me about that! Currently ZZC plugin is already able to work with V1, you can check it at branch called `migrate-to-v1` in this repo. There is still no polyphony support, so I'm working on it.
What's about ZZC Phaseque - currently its codebase also prepared and tested with V1 (sources are closed). I'm working on performance optimization of Phaseque and of course plan to add polyphony support for it.

![Screenshot at 2019-06-06 23-17-47](https://user-images.githubusercontent.com/1945127/59063691-53524400-88b1-11e9-85a7-17d03e9dd06b.png)

**Comment by Torinbob** [comment]
Brilliant - thank you!

**Comment by Torinbob** [comment]
Hi ZZC - is there a mac build beta I could check out by any chance? I'm not to concerned about polyphony but would love to see the clock, divider and function generator in V1! thanks.

**Comment by stephanepericat** [comment]
awesome :)

**Comment by zezic** [comment]
Hi, @Torinbob

There is no build for Mac yet, but I'm working on porting to 1.0 at the moment.
Yesterday I've added polyphony to SC-VCA, it was not so smooth as I expected (because SIMD optimization is a new thing for me), but I think it should make me go better with other modules.
Today my plan is to add polyphony to Divider, FN-3 and, maybe, SRC.
After that I plan to add poly to Phaseque and create a request for updating all ZZC modules in VCV Library.

I plan to finish this migration till June 30, so, I think, it will be available in Library soon and it's better to not release the unfinished modules to not break the compatibility.

**Comment by FMTolstoevsky** [comment]
Есть ли надежда увидеть ваши замечательные модули версии 1 в течение ближайшей недели, Сергей? Каждый день проверяю github, вижу какие-то подвижки в процессе, но, видимо, что-то вас пока смущает? 
С наилучшими пожеланиями,
Тигран.

**Comment by zezic** [comment]
@FMTolstoevsky, спасибо, что интересуетесь. Были небольшие трудности, но сегодня я отправил запрос на включение обновлённых модулей в библиотеку: https://github.com/VCVRack/library/issues/552#issuecomment-508985095
SC-VCA и FN-3 будут полифоническими сразу, поддержка полифонии в Divider и SRC будет добавлена позже, Clock и SH-8 останутся монофоническими.

**Comment by FMTolstoevsky** [comment]
Отличные новости, очень рад и надеюсь, что команда проверяльщиков (cschol и его коллеги :) не станет мутузить ваш пакет столь же долго, как, например, товарища Bidoo ;) 
Ну а по поводу полифонии - ИМХО это дело добровольное (для авторов), если есть силы и желание, такая добавка конечно приветствуется, но и без нее я раньше прекрасно обходился.

**Comment by VegaDeftwing** [comment]
How is progress on Phaseque coming? Do you have an estimated time to completion?

**Comment by zezic** [comment]
@VegaDeftwing I've done most of possible adaptations of it to Rack 1.1 now. I've sent it to review and I think, it should appear in library today or tomorrow if it has no any issues (depends on VCV Rack library team).

**Comment by zezic** [comment]
@VegaDeftwing Phaseque 1.1.0 was added to the library
