### ISSUE TITLE
Reset Handling

### ISSUE THREAD

**Issue by Stubs42** [zezic/ZZC#43]
Hi,
To keep clock dividers in sync with the clock, the clock dividers have to be reset with the clock.
The clock dividers should behave similar to the clock itself but the don't.
The clock resets its phase and delivers the first clock tick on start which is exactly what I would expect but the clock dividers deliver a clock tick on reset and miss the the first clock tick when starting.
I'm a great fan of the idea of a phased clock and would use ZZC clock and its dividers as my number one clock if the clock dividers reset behavior would just reset and deliver the first clock tick when starting again.

**Comment by zezic** [comment]
Oh, hi, @Stubs42.
I don't understand how it was possible for me to miss your message before that moment, I'm sorry.
The feature will be available in the next release of ZZC as an option in context menu of Divider module. I will inform you here additionally when release will become available in VCV Library.
Thank your for your feature request!

**Comment by zezic** [comment]
Added in v1.1.1
