### ISSUE TITLE
MIDI mapping to knobs does not work with ZZC modules

### ISSUE THREAD

**Issue by ContemporaryInsanity** [zezic/ZZC#51]
Mapping to buttons seems ok but I haven't tested extensively.

**Comment by zezic** [comment]
Which particular module are you talking about? If it's about expression X/Y displays of Phaseque or its "MUTA" knob , then yes, they don't support MIDI mapping yet. But other knobs should work fine.
Can you specify the module and its knob where mapping does not work?

**Comment by ContemporaryInsanity** [comment]
Strange, I was attempting to map a x-touch controller to Phaseque voltage knobs, having gone back for another look it's now working, perhaps I was doing something stupid, not properly awake yet, apologies.
