### ISSUE TITLE
Feature Request: SH-8 voltage range options in right-click menu?

### ISSUE THREAD

**Issue by espenstoro** [zezic/ZZC#52]
It would be super useful to be able to set the voltage range to 10/-10, 5/-5, and so on. Is that something you would consider? One of the most useful modules already, but I miss that. The range is often a bit too small for many things. :)

Cheers, 
E

**Comment by zezic** [comment]
Sure. I think it would be nice to have it as a menu option.

**Comment by zezic** [comment]
Added in v1.1.1
