### ISSUE TITLE
SRC displaying and outputting the wrong note

### ISSUE THREAD

**Issue by flydoggy** [zezic/ZZC#54]
I think the bug is that the display on the SRC module is displaying the wrong thing - when you dial in C#3 it displays C#4. There are three reasons I think this:

When you go up a semitone from C3 the display jumps to C#4.
If you add a Hot Tuna to your patch you can see that when it thinks the output is C#3, SRC displays C#4.
Look at the knob positions in the screenshot: Coarse in the same place, Fine one semitone up, but the displays say C3 and C#4:

**Comment by zezic** [comment]
@flydoggy can you upload a minimal patch able to reproduce that behavior?

**Comment by flydoggy** [comment]
[https://patchstorage.com/src-bug/](url)

**Comment by zezic** [comment]
Thank you! Confirmed. Probably, it's a bug related to some rounding precision issues. I will rewrite it and notify about the fix in this thread.

**Comment by zezic** [comment]
Fixed in v1.1.1
