### ISSUE TITLE
Win 10 build issue

### ISSUE THREAD

**Issue by SteveRussell33** [zezic/ZZC#59]
``
g++  -std=c++11 -Wsuggest-override   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Div.cpp.o src/Div.cpp
src/Div.cpp: In member function 'virtual void Div::process(const rack::engine::Module::ProcessArgs&)':
src/Div.cpp:46:13: warning: unused variable 'fraction' [-Wunused-variable]
   46 |       float fraction = fractionParam >= 0.f ? fractionDisplay : 1.f / fractionDisplay;
      |             ^~~~~~~~
In file included from src/Div.cpp:2:
src/DivCore.hpp: In instantiation of 'void DivCore<T>::process(T) [with T = rack::simd::Vector<float, 4>]':
src/Div.cpp:56:49:   required from here
src/DivCore.hpp:30:25: error: no matching function for call to 'abs(rack::simd::Vector<float, 4>&)'
   30 |     T bigDeltaMask = abs(phaseInDelta) > 0.1f;
      |                      ~~~^~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/include/c++/9.2.0/cstdlib:75,
                 from ../../include/common.hpp:5,
                 from ../../include/rack.hpp:6,
                 from ../../include/rack0.hpp:2,
                 from src/ZZC.hpp:1,
                 from src/Div.cpp:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:411:15: note: candidate: 'int abs(int)'
  411 |   int __cdecl abs(int _X);
      |               ^~~
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:411:23: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'int'
  411 |   int __cdecl abs(int _X);
      |                   ~~~~^~
In file included from C:/msys64/mingw64/include/c++/9.2.0/cstdlib:77,
                 from ../../include/common.hpp:5,
                 from ../../include/rack.hpp:6,
                 from ../../include/rack0.hpp:2,
                 from src/ZZC.hpp:1,
                 from src/Div.cpp:1:
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:79:3: note: candidate: 'constexpr long double std::abs(long double)'
   79 |   abs(long double __x)
      |   ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:79:19: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'long double'
   79 |   abs(long double __x)
      |       ~~~~~~~~~~~~^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:75:3: note: candidate: 'constexpr float std::abs(float)'
   75 |   abs(float __x)
      |   ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:75:13: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'float'
   75 |   abs(float __x)
      |       ~~~~~~^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:71:3: note: candidate: 'constexpr double std::abs(double)'
   71 |   abs(double __x)
      |   ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:71:14: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'double'
   71 |   abs(double __x)
      |       ~~~~~~~^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:61:3: note: candidate: 'long long int std::abs(long long int)'
   61 |   abs(long long __x) { return __builtin_llabs (__x); }
      |   ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:61:17: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'long long int'
   61 |   abs(long long __x) { return __builtin_llabs (__x); }
      |       ~~~~~~~~~~^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:56:3: note: candidate: 'long int std::abs(long int)'
   56 |   abs(long __i) { return __builtin_labs(__i); }
      |   ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/std_abs.h:56:12: note:   no known conversion for argument 1 from 'rack::simd::Vector<float, 4>' to 'long int'
   56 |   abs(long __i) { return __builtin_labs(__i); }
      |       ~~~~~^~~
make: *** [../../compile.mk:69: build/src/Div.cpp.o] Error 1
``

**Comment by zezic** [comment]
@SteveRussell33 what's your Rack SDK version?

**Comment by SteveRussell33** [comment]
Latest rack dev source.

**Comment by zezic** [comment]
@SteveRussell33 OK. Then, please, use the 6af944e26284a51b0518fd3e8bd3d9162f181b00 commit for now. I will get rid of this problem later, probably I need to explicitly mention a `simd` namespace.
