### ISSUE TITLE
Phaseque crashes VCV on Mac

### ISSUE THREAD

**Issue by Torinbob** [zezic/ZZC#60]
I just bought Phaseque

Looking forward to trying it but unfortunately it is completely unusable Mac as it crashes VCV as soon as it is dragged into the Rack from the module browser.

Log text says:

[11.372 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
10: 1   Rack                                0x00000001068163cd _ZL18fatalSignalHandleri + 45
9: 2   libsystem_platform.dylib            0x00007fff5cd8db5d _sigtramp + 29
8: 3   ???                                 0x0000000000000000 0x0 + 0
7: 4   AMDRadeonX4000GLDriver              0x00000000160d6f9c gldUpdateDispatch + 243
6: 5   GLEngine                            0x00007fff3a98e556 gleDoDrawDispatchCore + 630
5: 6   GLEngine                            0x00007fff3a94ec13 glDrawArrays_ACC_Exec + 229
4: 7   Rack                                0x00000001067f8600 _ZL18glnvg__renderFlushPv + 2608
3: 8   Rack                                0x00000001067bda1a nvgEndFrame + 26
2: 9   Rack                                0x000000010682e32b _ZN4rack6Window3runEv + 1451
1: 10  Rack                                0x0000000106815efa main + 1434
0: 11  Rack                                0x00000001067af034 start + 52

**Comment by zezic** [comment]
Can you please try the light graphics instead of standard? Here is an archive:
[ZZC-Phaseque_Light_Graphics.zip](https://github.com/zezic/ZZC/files/3855930/ZZC-Phaseque_Light_Graphics.zip)

**Comment by zezic** [comment]
@Torinbob Ah, I've just read your message on Facebook. It seems like light graphics pack helped. I will prepare a release and notify you and others when it reaches the VCV Library.

**Comment by zezic** [comment]
By the way, @Torinbob, what's your Mac model and graphics adapter? May be this info will help to fix some bug present in Rack or NanoVG.

**Comment by Torinbob** [comment]
It’s a 2018 MacBook Pro 2.7 gHz with Radeon Pro 560x graphics.

**Comment by zezic** [comment]
@Torinbob ZZC Phaseque 1.1.2 with light graphics is available in the library.

**Comment by odhondt** [comment]
I also have the crash problem with 1.1.2 in high sierra. How to switch to light graphics mode?

**Comment by zezic** [comment]
@odhondt Please, let me know your email by sending something to zezic51@yandex.ru
I will send you a build with a potential fix.
