### ISSUE TITLE
Phaseque: Always hang on exit on Mac

### ISSUE THREAD

**Issue by sanderbaan** [zezic/ZZC#68]
Whenever there is a Phaseque in the patch when quiting VCV Rack it hangs. Tried also with a patch with just Phaseque and still hangs, have to force quit. Hang also occurs when I try to delete Phaseque after restarting. See hanglog attached. Mac OS 10.14

[hangphaseque.txt](https://github.com/zezic/ZZC/files/3883478/hangphaseque.txt)

**Comment by zezic** [comment]
Thank you for the report and especially for the provided dump, @sanderbaan.

Can you do the following?
1. Navigate to the `Documents/Rack/plugins-v1/ZZC-Phaseque` folder.
2. Archive the `res` folder (Zip archive will do) and attach it with the reply to this thread.
3. Download the next alternative version of graphics: [ZZC-Phaseque_Light_Graphics.zip](https://github.com/zezic/ZZC/files/3883504/ZZC-Phaseque_Light_Graphics.zip)
4. Replace the contents of your existing Phaseque `res` folder with the `res` folder from the archive I attached and check if it helps.

**Comment by sanderbaan** [comment]
[res.zip](https://github.com/zezic/ZZC/files/3883510/res.zip)

**Comment by sanderbaan** [comment]
with the new gfx does not hang when nothing is connected(did before) and in default state(init), when I randomize all patterns and then try to close it hangs again

**Comment by zezic** [comment]
That's pretty strange because it turned out that contents of these 2 folders were identical. 
Can you attach a dump with the latest case, please? I mean, when it hangs when closing the Rack after randomizing.
Also, please, let me know your e-mail by sending something to zezic51@yandex.ru
I will prepare several builds to narrow down the issue.

**Comment by quantegy** [comment]
Also getting this when browsing the sequencer category in Rack, if the Phaseque is in the patch, as well as when I try to remove the module from the Rack patch, it will cause Rack to hang. I am using Mac Catalina.

**Comment by jhonnyrb** [comment]
Hi, who can help me with vcv rack, the program closes, gives an error. i have mac catalina 10.15.2

**Comment by zezic** [comment]
Hello, @jhonnyrb!
I will publish the bugfix release until September 7th. The thing is that alongside with the bugfix I started to develop a new set of features and performance optimizations and it took more time than I expected.
Now, as the bug becomes too common among macOS users I decided to decouple it from the new features I'm developing and to release it separately but sooner. 

For now, until the bugfix get released, please, disable the ZZC-Phaseque plugin by removing its folder from the `plugins` folder inside the [Rack user folder](https://vcvrack.com/manual/FAQ#where-is-the-rack-user-folder).

**Comment by jhonnyrb** [comment]
thanks for answering, the folder does not appear in the rack, do we have to wait for the update to launch?

regards..

**Comment by zezic** [comment]
@jhonnyrb When opening the user folder do you have the `plugins-v1` folder inside it?
If yes, then open it and you should see a bunch of plugin folders inside, one of them will be the folder named `ZZC-Phaseque`. Remove the `ZZC-Phaseque` folder. This way you will be able to disable the Phaseque plugin temporarily.

After doing that, when running the Rack it will ask you to install the Phaseque plugin, but don't accept it until the fix get released.
The fixed release will have a version number of `v1.1.3` and I will notify you as soon as it will be available.

**Comment by zezic** [comment]
@jhonnyrb That's interesting. So, you saying that when you transfer VCV Rack to applications it gives the error (because of ZZC-Phaseque module), but when you run VCV Rack from Downloads folder, then it runs well. Did I got you correctly?

**Comment by jhonnyrb** [comment]
@zezic it is correct i run it from download folder and it works fine. If I see another change I will notify you. thank you very much for your help.

**Comment by mhetrick** [comment]
@zezic Sorry to bump this, but was 1.1.3 ever released? I'm still experiencing hangs with Phaseque on my Mac. It works perfectly on Windows and is an excellent device.

**Comment by zezic** [comment]
@mhetrick Thank you for bumping this. I sent you email with the version to test. I hope, it will fix the issue and that it will be released soon.

**Comment by zezic** [comment]
The issue should be fixed now.
