### ISSUE TITLE
ZZC Clock feature request: Optional bipolar +/-5V phase output

### ISSUE THREAD

**Issue by anlexmatos** [zezic/ZZC#73]
I've found that the ZZC Clock makes an excellent pair with my [Algomorph](https://github.com/anlexmatos/FM-Delexander) module: by patching the ZZC Clock's gate and phase outputs to Algomorph's Morph and Trigger inputs, circular morphing between Algomorph's three stored algorithms is enabled.

There's just one minute issue: Algomorph is designed around pivoting left or right from a center algorithm of the user's choice, and therefore it expects +/-5V at its Morph CV input, and so a -5V offset is required between our modules:

![image](https://user-images.githubusercontent.com/12039110/95140699-80309880-073d-11eb-9a93-45e1370857cb.png)

I've considered adding an option to Algomorph's contextual menu to enable 0V-10V Morph CV input, but it's my thinking that it makes more sense to have this on ZZC Clock's end. Having a clock which centers its phase around the middle of a beat (0v = half-phase) seems to make more sense than having a module which denotes neutral-position as 5V, I think.

In any case I'm not totally opposed to adding the option on my end, but I figured I would run the idea by you to see what you think.

**Comment by zezic** [comment]
@anlexmatos Done and waiting for publishing on VCV Library. Binary builds are already available: https://github.com/zezic/ZZC/releases/tag/v1.1.3

**Comment by anlexmatos** [comment]
Excellent. Thank you!

**Comment by zezic** [comment]
Released on VCV LIbrary.
