### ISSUE TITLE
Invalid license ID in plugin.json

### ISSUE THREAD

**Issue by cschol** [zezic/ZZC#75]
It has been a while since the plugin was last updated. We now have a check for invalid license IDs in place.

```
ZZC] Validating plugin.json...FAILED
[ZZC] Issues found in `plugin.json`:

Invalid license ID: GPL-3.0
-- License must be a valid Identifier from https://spdx.org/licenses/
```

It should either be `GPL-3.0-only` or `GPL-3.0-only-or-later`.

**Comment by zezic** [comment]
Thank you, fixed with e64377b49452d204ab6a8999978eb64543144eac
