### ISSUE TITLE
VCV Rack 2 Compatibility

### ISSUE THREAD

**Issue by squinkylabs** [zezic/ZZC#80]
I see some speculation about whether you are going to port this to 2.0.

Some info: https://github.com/squinkylabs/Demo/blob/main/docs/license-issues.md

**Comment by squinkylabs** [comment]
sounds good.

**Comment by zezic** [comment]
Haha, yes! But don't close it, let me finish the migration 😄

**Comment by zezic** [comment]
Released on VCV Library.
