### ISSUE TITLE
Please use GPLv3.0+ instead of GPLv3.0-only license

### ISSUE THREAD

**Issue by falkTX** [zezic/ZZC#86]
Hi again,
Is there a specific reason ZZC modules are licensed as GPLv3.0-only, instead of the more common GPLv3.0+?

This is a blocker for integrate your modules into Cardinal, as the only license possible would then be GPLv3.0, which is not very nice...
If using GPLv3.0+ we could mix it together with GPLv2.0+ and future GPLv4, v5 etc

Using GPLv3.0-only as the code license is problematic going forward, if GPLv4 ever gets released.
(GPLv4 supposedly will add restrictions for AI scrappers, like done on GitHub, stuff that reads code and "generates" new stuff via AI. Currently GPL does not provide anything against it)

Is this something you would be willing to change? I can answer license related questions if you have any, since I have been dealing with those for a long time (but as you know I am no lawyer, just an open-source developer and packager)

If you do not want to change the license, please let me know, I will then have remove your modules from the Cardinal project though.

**Comment by zezic** [comment]
I read somewhere (sorry, can't find the article) that it's better to control any upstream license updates by fixing the projects current license to the particular version. Who knows what will be added to GPLv5?
I would like my modules to be **included** to Cardinal project, but I also would like to keep my code safe and protected against any possible harmful GPL upgrades. Today's _social environment_ can force very unpredictable and absurd actions to be issued against developers and other IT people.
What's your opinion about that? And again, I want my modules to be included in Cardinal, it's a good alternative Rack port with its own benefits.

**Comment by falkTX** [comment]
This is a question of trust, and keeping future compatibility,

Projects that had similar ideas of yours in mind made in the past (GPLv2-only when GPLv3 was not yet a thing), but which the authors stopped developing for some reason or which commits comes from 3rd parties that are not always easy to track down (so everyone who contributed could say yes to license changes), are now forever stuck with GPLv2-only.
As we go forward these projects will slowly go into irrelevance, or be rewritten so they can keep being used.

We hope it is not the case, but if something happens to you that you are no longer able to update the code and/or license, it will also forever be GPLv3-only.

Personally I do not see a reason to distrust the Free Software Foundation when it comes to making GPLv4.

**Comment by falkTX** [comment]
What about using an alternative, non-GPL license, that is still compatible with GPL in general?
I am guessing BSD/ISC is not a good option, since you went GPL in the first place, 

https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses lists a few.

Artistic2 and MPL2 are somewhat common and the most similar to GPL afaik.

**Comment by dromer** [comment]
I think if you do not trust FSF then you shouldn't use GPL license in the first place.

It would then be best to pick a different license for your modules so that you can ensure that your rights are met and they can stay included in Cardinal :)

**Comment by falkTX** [comment]
Just to let you know, I have removed your ZZC modules from Cardinal just now.
Will be glad to add them back if the license situation changes and becomes compatible.

**Comment by zezic** [comment]
@falkTX Sorry for making all involved people to wait too long. I changed (268c15711a7fe184970b1525c98f17e72db64af5) the license to GPL-3.0-or-later.

_P.S. I feel like currently it will take significantly less energy to "just change it and forgot" rather that trying to find the optimal alternative and it's better to not hurt the existing user experience. I'm still somewhat skeptical about future FSF course, but let's see how it goes._

**Comment by dromer** [comment]
I would assume that if you choose the GPL you would not have skepticism towards FSF, but I hope you will then find a suitable candidate for re-licensing in the future if that remains your stance.

All in good will, at least I hope!

**Comment by falkTX** [comment]
I was not expecting that, so now pleasantly surprised.
Thanks for reconsidering, and sorry for pushing a bit, licenses are just not something we can joke around for such a project.

Will add it back again shortly :smile:
