### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [zezic/ZZC#87]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
VerticalRatioDisplayWidget() {
  font = APP->window->loadFont(asset::plugin(pluginInstance, "res/fonts/DSEG/DSEG7ClassicMini-Italic.ttf"));
};
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by zezic** [comment]
Oh, really. I totally forgot about that point! Thank you! I will post the new commit hash inside library issues right now.
Fixed by 3f12cb06b974e7b9c6c80d84cff955c7c680d5b4
