### ISSUE TITLE
Artwork license clarification request

### ISSUE THREAD

**Issue by falkTX** [zezic/ZZC#89]
On #37 you mention the artwork not being under GPL, with some notes added in the LICENSE.txt file.
But reading the top of that file only copyright is mentioned, no artwork license terms.
Except the obvious "Please, contact author [...] if you want to use graphics for public works", but that is not really a license.

So what is the license for the artwork files then?

**Comment by zezic** [comment]
Can you suggest a license? For sure, I would like to give a permission to include these modules with their graphics in any host where they will act and perform like they currently do. So, if they look and act like ZZC modules – yes, they can keep their current artwork with logos, controls and anything.

**Comment by falkTX** [comment]
CC-BY-SA is the one that matches in spirit with GPL - use it for whatever you want, but any changes need to be published in the same way, same license.

Then some add in -NC for non-commercial, or -ND for non-derivatives, or both.

Alternatively you can also use GPL for artwork, that is valid too.

**Comment by falkTX** [comment]
Hey, any resolutions on this?
I plan to release Cardinal is 12 days, that target date is slowly approaching. I will try to help if you still have any questions.

**Comment by zezic** [comment]
@falkTX I changed the panel graphics license to CC BY-NC-SA 3.0. ZZC logo is now free to use anywhere within ZZC modules as long as they look and perform like their original versions designed for VCV Rack.
I hope this will allow to include ZZC into Cardinal!

**Comment by falkTX** [comment]
Kinda.. "as long as they look and perform like the original" is not really something enforceable, having such text there is pointless and problematic. Cardinal now runs on BSD which afaik Rack never did, nor did any Rack dev tried. Is porting to new platforms "performing like the original"? The original never worked on them so it could be...
Any such text you try to add is always going to be problematic.

Also why CC 3.0? Why not 4.0?

**Comment by falkTX** [comment]
Here is a proposal;

ZZC Panel Graphics are licensed under CC BY-NC-SA .0:
https://creativecommons.org/licenses/by-nc-sa/4.0/

The ZZC Logo is Copyright (c) 2019 Sergey Ukolov and cannot be used in derivative works.
ZZC plugin ports to other environments than VCV Rack that leave graphics intact do not constitute a derivative work.

**Comment by zezic** [comment]
> Kinda.. 

I agree. This restriction is too blurry.

> Here is a proposal

Accepted!

**Comment by falkTX** [comment]
Thanks, I think that works quite nicely then! Will re-add your modules.
