### ISSUE TITLE
SKODANext font license missing

### ISSUE THREAD

**Issue by falkTX** [zezic/ZZC#90]
You provide 3 sets of fonts: DSEG, Nunito and SKODANext.
The first 2 provide clear license terms, the last one is missing a license altogether.

What are its origins? What is its license?

**Comment by zezic** [comment]
That's good question. I will try to register at Skoda website to find out more about the font. Maybe I will have to change it to some other similar font like Montserrat.

**Comment by zezic** [comment]
`SKODANext-Regular.ttf` has been eliminated with the d1643cc2b8a843938fbf6d15d9226a57faefce65. It's not used for any of the finished modules anyway, it will be better to find similar font with clear license to migrate to.
